/**
 * Environment variable name constants.
 * These match the variables documented in .env.example.
 * Values are NOT exposed here — only names.
 */
export const ENV_KEYS = {
  // Application
  NODE_ENV: 'NODE_ENV',
  APP_NAME: 'APP_NAME',
  APP_URL: 'APP_URL',
  API_URL: 'API_URL',

  // API Server
  API_PORT: 'API_PORT',
  API_PREFIX: 'API_PREFIX',
  API_VERSION: 'API_VERSION',
  API_BODY_LIMIT_MB: 'API_BODY_LIMIT_MB',

  // JWT
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_ACCESS_EXPIRY: 'JWT_ACCESS_EXPIRY',
  JWT_REFRESH_EXPIRY_DAYS: 'JWT_REFRESH_EXPIRY_DAYS',

  // Cookie
  COOKIE_SECRET: 'COOKIE_SECRET',
  COOKIE_SAME_SITE: 'COOKIE_SAME_SITE',
  COOKIE_DOMAIN: 'COOKIE_DOMAIN',

  // Database
  DATABASE_URL: 'DATABASE_URL',

  // Redis
  REDIS_URL: 'REDIS_URL',

  // CORS
  CORS_ORIGIN: 'CORS_ORIGIN',

  // Rate Limiting
  RATE_LIMIT_WINDOW_MS: 'RATE_LIMIT_WINDOW_MS',
  RATE_LIMIT_MAX_REQUESTS: 'RATE_LIMIT_MAX_REQUESTS',
  RATE_LIMIT_AUTH_MAX: 'RATE_LIMIT_AUTH_MAX',
  RATE_LIMIT_AUTH_WINDOW_MS: 'RATE_LIMIT_AUTH_WINDOW_MS',
  RATE_LIMIT_FALLBACK_AUTH_MAX: 'RATE_LIMIT_FALLBACK_AUTH_MAX',
  RATE_LIMIT_FALLBACK_AUTH_WINDOW_MS: 'RATE_LIMIT_FALLBACK_AUTH_WINDOW_MS',

  // Logging
  LOG_LEVEL: 'LOG_LEVEL',

  // Frontend
  NEXT_PUBLIC_API_URL: 'NEXT_PUBLIC_API_URL',
  NEXT_PUBLIC_APP_NAME: 'NEXT_PUBLIC_APP_NAME',
} as const;
